export default {
  ADD_NEW_POKEMONS: "ADD_NEW_POKEMONS",
  ADD_POKETREE: "ADD_POKETREE",
  SET_POKEMON_TYPES: "SET_POKEMON_TYPES",
  CHANGE_MAX_RANGE: "CHANGE_MAX_RANGE",
  TOGGLE_TYPE_FILTER: "TOGGLE_TYPE_FILTER",
  SET_POKEMON_RANGE: "SET_POKEMON_RANGE",
  FILTER_BY_NAME: "FILTER_BY_NAME",
  SORT_ID_ASCENDING: "SORT_ID_ASCENDING",
  SORT_ID_DESCENDING: "SORT_ID_DESCENDING",
  SORT_NAME_ASCENDING: "SORT_NAME_ASCENDING",
  SORT_NAME_DESCENDING: "SORT_NAME_DESCENDING",
};